- name: catalogue 
  hosts: catalogue
  become: yes
  tasks:
  - name: setting up nodejs souce
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: installing node js
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: checkroboshop user exist or not 
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true 

  - when: out.rc !=0
    name: create user roboshop  
    become: yes
    ansible.builtin.user:
      name: roboshop

  - name: print the directory stats
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - when: directory.stat.exists == False
    name: create /app directory   
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the application code and extract
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command:
    args:   
      chdir: /app

  - name: copy catalogue.service to /etc/systemd/system/catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: starting and enabling catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: true

  - name: copying mongodb.repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: installing mongodb-org-shell
    ansible.builtin.yum:
      name: mongodb-org-shell 
      state: installed
  
  - name: loading schema
    ansible.builtin.shell: mongo --host mongodb.joindevops.cloud < /app/schema/catalogue.js

  - name: restart catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: true

